blockchain_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls  import url, include
from doctor import views as doctor_views

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^$', doctor_views.index, name = 'root'),
    url(r'^doctor/', include('doctor.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/signup$', doctor_views.signup, name='signup'),
]

doctor/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'doctor'

urlpatterns = [
                  url(r'^$', views.index, name='index'),
                  url(r'^profile/(?P<pk>[0-9]+)/$', views.profile, name='profile'),
                  url(r'^doctor_certification/(?P<pk>[0-9]+)$', views.doctor_certification, name='doctor_certification'),
                  url(r'^individual_certification/(?P<pk>[0-9]+)$', views.individual_certification, name='individual_certification'),
                  #url(r'^enterprise_certification/(?P<pk>[0-9]+)$', views.enterprise_certification, name='enterprise_certification'),
                  url(r'^doctor_form/(?P<pk>[0-9]+)$', views.doctor_form, name='doctor_form'),
                  url(r'^for_user/(?P<pk>[0-9]+)$', views.for_user, name='for_user'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

doctor/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Category(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_category')
    sort = models.CharField(max_length=20, blank=True)

    def __str__(self):
        return '{} {}'.format(self.sort, self.user)


class Doctor(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_doctor')
    name = models.CharField(max_length=30, blank=False)
    medical_name = models.CharField(max_length=30, blank=False)
    address = models.CharField(max_length=200, blank=False)
    phone_number = models.CharField(max_length=20, blank=False)
    license_number = models.IntegerField(blank=False)
    certification = models.FileField(upload_to='documents/%Y/%m/%d/')
    uploaded_at = models.DateTimeField(auto_now_add=True)


# class Enterprise(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='enterprise_user')
#     enterprise_name = models.CharField(max_length=20, blank=True)
#     enterprise_category = models.CharField(max_length=30, blank=True)
#     uploaded_at = models.DateTimeField(auto_now_add=True)

doctor/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Doctor

class UserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user


class DoctorForm(forms.ModelForm):
    class Meta:
        model = Doctor
        fields = (
            'name',
            'medical_name',
            'address',
            'phone_number',
            'license_number',
            'certification'
        )
#
# class EnterpriseForm(forms.ModelForm):
#     class Meta:
#         model = Enterprise
#         fields = ('enterprise_name', 'enterprise_category')

doctor/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate
from .forms import UserCreationForm, DoctorForm
from .models import Category, Doctor
from django.contrib import messages

def index(request):
    return render(request, 'doctor/index.html')

def profile(request, pk):
    user = User.objects.get(pk=pk)
    context = {user: user}
    return render(request, 'doctor/profile.html', context)

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('doctor:index')
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})


def doctor_certification(request, pk):
    user = User.objects.get(pk=pk)
    category = Category.objects.filter(sort='DOCTOR')

    if request.method == 'POST':
        form = DoctorForm(request.POST, request.FILES)
        if form.is_valid():
            form = form.save(commit=False)
            form.user = user
            # Category 저장
            for i in category:
                if user == i.user:
                    messages.error(request, '이미 등록!', extra_tags='alert')
                    return redirect('doctor:index')
            form.save()
            Category.objects.create(user=user, sort='DOCTOR')

            return redirect('doctor:index')
    else:
        form = DoctorForm()
    return render(request, 'doctor/doctor_certification.html', {
        'form': form,
    })


def individual_certification(request, pk):
    user = User.objects.get(pk=pk)
    category = Category.objects.filter(sort='INDIVIDUAL')
    for i in category:
        if user == i.user:
            messages.warning(request, '이미 등록')
            return redirect('doctor:index')
    Category.objects.create(user=user, sort='INDIVIDUAL')
    messages.success(request, '등록 완료')
    return redirect('doctor:index')

# def enterprise_certification(request, pk):
#     user = User.objects.get(pk=pk)
#     category = Category.objects.filter(sort='ENTERPRISE')
#
#     if request.method == 'POST':
#         form = EnterpriseForm(request.POST)
#         if form.is_valid():
#             form = form.save(commit=False)
#             form.user = user
#
#             # Category 저장
#             for i in category:
#                 if user == i.user:
#                     messages.warning(request, '이미 등록')
#                     return redirect('doctor:index')
#             form.save()
#             Category.objects.create(user=user, sort='ENTERPRISE')
#             messages.success(request, '등록 완료')
#             return redirect('doctor:index')
#     else:
#         form = EnterpriseForm()
#     return render(request, 'doctor/enterprise_certification.html', {
#         'form': form,
#     })

def doctor_form(request, pk):
    user = User.objects.get(pk=pk)
    doctor_info = Doctor.objects.get(user=user)
    context = {
        'id': user.username,
        'name': doctor_info.name,
        'medical_name': doctor_info.medical_name,
        'address': doctor_info.address,
        'phone_number': doctor_info.phone_number,
        'license_number': doctor_info.license_number,
    }
    return render(request, 'doctor/doctor_form.html', context)


def for_user(request, pk):

    return render(request, 'doctor/for_user.html')

doctor/templates/doctor/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <title>{% block title %} {% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>INDEX</title>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans|Raleway|Candal">
    <link rel="stylesheet" type='text/css' href="{% static 'doctor/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type='text/css' href="{% static 'doctor/css/font-awesome.min.css' %}">
    <link rel="stylesheet" type='text/css' href="{% static 'doctor/css/style.css' %}">
    {% block header %} {% endblock %}
</head>

<body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="60">
<!--banner-->
{% load staticfiles %}
        <nav class="navbar navbar-default top-nav-collapse">
            <div class="container">
                <div class="col-md-12">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="{% url 'doctor:index' %}"><img src="{% static 'doctor/img/logo.png' %}" class="img-responsive" style="width: 140px; margin-top: -16px;"></a>
                    </div>
                    <div class="collapse navbar-collapse navbar-right" id="myNavbar">
                        <ul class="nav navbar-nav">
                            <li class=""><a href="#service">Services</a></li>
                            <li class=""><a href="#aboutus">About</a></li>
                            {% if user.is_active %}
                                <li>
                                    <a href="{% url 'doctor:doctor_form' user.pk %}">DOCTOR'S FORM</a>
                                </li>
                                <li>
                                    <a href="{% url 'logout' %}">LOGOUT</a>
                                </li>
                                <li>
                                    <a href="{% url 'doctor:profile' user.pk %}">MY PAGE</a>
                                </li>
                            {% else %}
                                <li>
                                <li class=""><a href="{% url 'login' %}">Sign in</a></li>
                                </li>
                                <li>
                                <li class=""><a href="{% url 'signup' %}">Sign up</a></li>
                                </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
{% block content %}
<section id="service" class="section-padding">
    <div class="container">

    </div>
</section>
{% endblock %}

</body>
</html>

doctor/templates/doctor/doctor_certification.html
{% extends 'doctor/base.html' %}

{% block title %} PROFILE {% endblock %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans|Raleway|Candal">
<link rel="stylesheet" type='text/css' href="{% static 'doctor/css/bootstrap.min.css' %}">
<link rel="stylesheet" type='text/css' href="{% static 'doctor/css/font-awesome.min.css' %}">
<link rel="stylesheet" type='text/css' href="{% static 'doctor/css/style.css' %}">
{% block content %}

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
            <div class="fieldWrapper">
                {{ field.errors }}
                {{ field.label_tag }}: {{ field }}
            </div>
        {% endfor %}
        <button type="submit">Upload</button>
    </form>

    <script src="{% static 'doctor/js/jquery.min.js' %}" type="text/javascript" ></script>
    <script src="{% static 'doctor/js/jquery.easing.min.js' %}" type="text/javascript" ></script>
    <script src="{% static 'doctor/js/bootstrap.min.js' %}" type="text/javascript" ></script>
    <script src="{% static 'doctor/js/custom.js' %}" type="text/javascript" ></script>

{% endblock %}

doctor/templates/doctor/doctor_form.html
{% extends 'doctor/base.html' %}

{% block title %} PROFILE {% endblock %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans|Raleway|Candal">
<link rel="stylesheet" type='text/css' href="{% static 'doctor/css/bootstrap.min.css' %}">
<link rel="stylesheet" type='text/css' href="{% static 'doctor/css/font-awesome.min.css' %}">
<link rel="stylesheet" type='text/css' href="{% static 'doctor/css/style.css' %}">
{% block content %}

    <h1>진단서 보내기!</h1>
    <form>
        <table>
            <tbody>
            <tr>
                <th>
                    ID
                </th>
                <td>
                    {{ id }}
                </td>
            </tr>
            <tr>
                <th>
                    이름
                </th>
                <td>
                    <input>
                </td>
            </tr>
            <tr>
                <th>
                    성별
                </th>
                <td>
                    <input>
                </td>
            </tr>
            <tr>
                <th>
                    나이
                </th>
                <td>
                    <input>
                </td>
            </tr>
            <tr>
                <th>
                    주소
                </th>
                <td>
                    <input>
                </td>
            </tr>
            <tr>
                <th>
                    병명
                </th>
                <td>
                    <input>
                </td>
            </tr>
            <tr>
                <th>
                    소견
                </th>
                <td>
                    <input>
                </td>
            </tr>
            <tr>
                <th>
                    비고
                </th>
                <td>
                    <input>
                </td>
            </tr>
            <tr>
                <th>
                    발행일
                </th>
                <td>
                    <input>
                </td>
            </tr>
            <tr>
                <th>
                    의료 기관명
                </th>
                <td>
                    <p>{{ medical_name }}</p>
                </td>
            </tr>
            <tr>
                <th>
                    주소 및 명칭
                </th>
                <td>
                    <p>{{ address }}</p>
                </td>
            </tr>
            <tr>
                <th>
                    전화번호
                </th>
                <td>
                    <p>{{ phone_number }}</p>
                </td>
            </tr>
            <tr>
                <th>
                    의사 면허번호
                </th>
                <td>
                    <p>{{ license_number }}</p>
                </td>
            </tr>
            <tr>
                <th>
                    의사 이름
                </th>
                <td>
                    <p>{{ name }}</p>
                </td>
            </tr>

            </tbody>
        </table>
        <button type="submit" name="" value="">보내기!</button>
    </form>


    <script src="{% static 'doctor/js/jquery.min.js' %}" type="text/javascript" ></script>
    <script src="{% static 'doctor/js/jquery.easing.min.js' %}" type="text/javascript" ></script>
    <script src="{% static 'doctor/js/bootstrap.min.js' %}" type="text/javascript" ></script>
    <script src="{% static 'doctor/js/custom.js' %}" type="text/javascript" ></script>

{% endblock %}

doctor/templates/doctor/enterprise_certification.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
</form>

doctor/templates/doctor/for_user.html
{% extends 'doctor/base.html' %}

{% block title %} PROFILE {% endblock %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans|Raleway|Candal">
<link rel="stylesheet" type='text/css' href="{% static 'doctor/css/bootstrap.min.css' %}">
<link rel="stylesheet" type='text/css' href="{% static 'doctor/css/font-awesome.min.css' %}">
<link rel="stylesheet" type='text/css' href="{% static 'doctor/css/style.css' %}">
{% block content %}

    <h1>사용자 방문기록 등등</h1>

    <script src="{% static 'doctor/js/jquery.min.js' %}" type="text/javascript" ></script>
    <script src="{% static 'doctor/js/jquery.easing.min.js' %}" type="text/javascript" ></script>
    <script src="{% static 'doctor/js/bootstrap.min.js' %}" type="text/javascript" ></script>
    <script src="{% static 'doctor/js/custom.js' %}" type="text/javascript" ></script>

{% endblock %}

doctor/templates/doctor/profile.html
{% extends 'doctor/base.html' %}

{% block title %} PROFILE {% endblock %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans|Raleway|Candal">
<link rel="stylesheet" type='text/css' href="{% static 'doctor/css/bootstrap.min.css' %}">
<link rel="stylesheet" type='text/css' href="{% static 'doctor/css/font-awesome.min.css' %}">
<link rel="stylesheet" type='text/css' href="{% static 'doctor/css/style.css' %}">
{% block content %}


    <ul>
        <li>{{ user }}</li>
        <li><a href="{% url 'doctor:doctor_certification' user.pk %}">Doctor</a></li>
        <li><a href="{% url 'doctor:individual_certification' user.pk %}">Individual</a></li>
        <li><a href="{% url 'doctor:for_user' user.pk %}">For User</a></li>
    </ul>

    <script src="{% static 'doctor/js/jquery.min.js' %}" type="text/javascript" ></script>
    <script src="{% static 'doctor/js/jquery.easing.min.js' %}" type="text/javascript" ></script>
    <script src="{% static 'doctor/js/bootstrap.min.js' %}" type="text/javascript" ></script>
    <script src="{% static 'doctor/js/custom.js' %}" type="text/javascript" ></script>

{% endblock %}